/*
 * Episteme - Java(TM) Tools and Libraries for the Advancement of Sciences.
 * Copyright (C) 2025-2026 - Silvere Martin-Michiellot and Gemini AI (Google DeepMind)
 */
package org.episteme.core.mathematics.ml.generative;

import java.util.Map;

/**
 * Represents a tool (function) that can be called by a generative model.
 */
public record Tool(String name, String description, Map<String, Object> parameters) {
    
    /**
     * Represents a call to a tool generated by the model.
     */
    public record Call(String toolName, Map<String, Object> arguments) {}
}
