/*
 * JScience - Java(TM) Tools and Libraries for the Advancement of Sciences.
 * Copyright (C) 2025-2026 - Silvere Martin-Michiellot and Gemini AI (Google DeepMind)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package org.jscience.psychology;

import java.io.Serializable;
import org.jscience.mathematics.numbers.real.Real;

/**
 * Models cognitive load based on Sweller's Cognitive Load Theory (CLT).
 * Provides methods to estimate intrinsic, extraneous, and germane load, and evaluate learning efficiency.
 *
 * @author Silvere Martin-Michiellot
 * @author Gemini AI (Google DeepMind)
 * @version 1.1
 * @since 1.0
 */
public final class CognitiveLoadModel {

    private CognitiveLoadModel() {}

    /**
     * Represents the components of cognitive load involved in a task.
     *
     * @param name       identifier for the task
     * @param intrinsic  inherent complexity of the material (0.0 to 1.0)
     * @param extraneous load generated by the manner of presentation (0.0 to 1.0, lower is better)
     * @param germane    load dedicated to processing and schema construction (0.0 to 1.0)
     */
    public record LoadFactor(
        String name,
        double intrinsic,
        double extraneous,
        double germane
    ) implements Serializable {}

    /**
     * Represents the resulting cognitive state of an individual performing a task.
     *
     * @param totalLoad         sum of all load components
     * @param availableResource remaining working memory capacity
     * @param isOverloaded      true if total load exceeds capacity
     * @param recommendation    instructional design suggestion
     */
    public record CognitiveState(
        double totalLoad,
        double availableResource,
        boolean isOverloaded,
        String recommendation
    ) implements Serializable {}

    /**
     * Evaluates the total cognitive load against a working memory capacity.
     * 
     * @param factor                the load factors of the task
     * @param workingMemoryCapacity the capacity of the learner (typically limited)
     * @return the evaluated cognitive state
     */
    public static CognitiveState evaluateLoad(LoadFactor factor, double workingMemoryCapacity) {
        double total = factor.intrinsic() + factor.extraneous() + factor.germane(); 
        // Note: Some models sum all three, others consider Germane as beneficial use of free space.
        // Here we sum them to check against total capacity.
        
        double available = workingMemoryCapacity - total;
        boolean overloaded = total > workingMemoryCapacity;

        String rec = "Optimal load balance.";
        if (overloaded) {
            rec = "Reduce extraneous load by simplifying presentation or reduce intrinsic load by segmentation.";
        } else if (factor.germane() < 0.2 && available > 0.3) {
            rec = "Potential to increase challenge to foster schema construction (increase germane load).";
        }

        return new CognitiveState(total, available, overloaded, rec);
    }

    /**
     * Estimates intrinsic load based on element interactivity.
     * Formula: I = log2(N_elements * N_interactions)
     * 
     * @param elements     number of distinct information elements
     * @param interactions number of interacting relationships between elements
     * @return estimated intrinsic load score
     */
    public static Real estimateIntrinsicLoad(int elements, int interactions) {
        if (elements <= 0) return Real.ZERO;
        // Simple heuristic model log2(N * (I+1))
        return Real.of(Math.log(elements * (interactions + 1.0)) / Math.log(2.0));
    }

    /**
     * Calculates the instructional efficiency of the learning task.
     * Efficiency = Germane / (Intrinsic + Extraneous)
     * Higher efficiency indicates more effort is spent on learning (germane) relative to overhead.
     * 
     * @param f the load factors
     * @return efficiency ratio
     */
    public static Real learningEfficiency(LoadFactor f) {
        double denominator = f.intrinsic() + f.extraneous();
        if (denominator == 0) return Real.ZERO; // Avoid division by zero
        return Real.of(f.germane() / denominator);
    }

    /**
     * Calculates a penalty for the Redundancy Effect.
     * The redundancy effect occurs when identical information is presented in multiple formats 
     * (e.g., on-screen text AND narration of that text), increasing extraneous load.
     *
     * @param identicalFormatCount number of redundant streams
     * @return calculated extraneous load penalty
     */
    public static double redundancyPenalty(int identicalFormatCount) {
        if (identicalFormatCount <= 1) return 0.0;
        return 0.1 * (identicalFormatCount - 1);
    }
}
