/*
 * JScience - Java(TM) Tools and Libraries for the Advancement of Sciences.
 * Copyright (C) 2025-2026 - Silvere Martin-Michiellot and Gemini AI (Google DeepMind)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package org.jscience.social.linguistics.loaders.tigerxml.core;

import java.io.File;

import org.jscience.social.linguistics.loaders.tigerxml.tools.GeneralTools;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;
import org.xml.sax.SAXException;
import org.xml.sax.SAXParseException;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;

/**
 * Provides static XML parsing functionality.
 * *          $Id: XMLParser.java,v 1.2 2007-10-21 17:47:08 virtualcall Exp $
 * @author Silvere Martin-Michiellot
 * @author Gemini AI (Google DeepMind)
 * @since 1.0
 */
public class XMLParser {

    /**
     * If this flag is set, the document will be parsed building a DOM tree,
     * if unset, the document will be parsed using SAX.
     */

    /**
     * The name of the XML file to be parsed
     */
    private String xmlFileName;

    /**
     * The first line in the XML corpus file. Ex: '<?xml version="1.0" ...'
     */

    /**
     * The higher this value the more process and debug information will
     * written to stderr.
     */
    private int verbosity = 0;

    public XMLParser(String xmlFileName) {
        init(xmlFileName);
    }

    public XMLParser(String xmlFileName, int verbosity) {
        this.verbosity = verbosity;
        init(xmlFileName);
    }

    private void init(String xmlFileName) {
        if ((setXMLFileName(xmlFileName)) && (this.verbosity > 2)) {
            System.err.println("org.jscience.social.ml.tigerxml.core.XMLParser: Initialized, XML Corpus: "
                    + xmlFileName + ".");
        }
    }

    /**
     * Parses the a given XML corpus file.
     *
     * @return The root element of the DOM built from this instances XML file.
     */
    public Element getDOMRootElement() {
        if (this.verbosity > 0) {
            System.err.println("org.jscience.social.ml.tigerxml.core.XMLParser: Parsing "
                    + this.xmlFileName + " and building DOM tree ...");
        }
        long time = System.currentTimeMillis();
        Document doc = null;
        DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();

        try {
            DocumentBuilder builder = factory.newDocumentBuilder();
            if (this.verbosity > 3) {
                System.err.println("org.jscience.social.ml.tigerxml.core.XMLParser: Using XML parser of "
                        + builder.getClass());
            }
            doc = builder.parse(new File(this.xmlFileName));
            // Admittedly, the following is not very nice.
            // But after hours of browsing the Java XML
            // documentation, I still see no other
            // possibility of getting the XML prolog.
        } catch (java.io.IOException ex) {
            ex.printStackTrace();
            System.err.println("org.jscience.social.ml.tigerxml.core.XMLParser: Could not open "
                    + this.xmlFileName
                    + ". Exiting.");
            System.exit(-1);
        } catch (SAXParseException spe) {
            // Error generated by the parser
            if (this.verbosity > 0) {
                System.err.println
                        ("\n** Parsing error"
                                + ", line " +
                                spe.getLineNumber()
                                + ", column " +
                                spe.getColumnNumber() +
                                ", uri " +
                                spe.getSystemId());
                System.err.println("   "
                        + spe.getMessage());
            }
        } catch (SAXException sxe) {
            Exception x = sxe;
            if (sxe.getException() != null) {
                x = sxe.getException();
            }
            x.printStackTrace();
        } catch (ParserConfigurationException pce) {
            pce.printStackTrace();
        }
        if (doc == null) return null;
        NodeList currentNodeList =
                doc.getElementsByTagName("corpus"); //corpus element list
        Element rootElement =
                (Element) currentNodeList.item(0); //corpus element
        if (this.verbosity > 3) {
            time = System.currentTimeMillis() - time;
            System.err.println("org.jscience.social.ml.tigerxml.core.XMLParser: Parsing XML consumed: " +
                    GeneralTools.timeConvert(time));
        }
        return rootElement;
    } // parseXMLcorp()

    public String getXMLFileName() {
        return this.xmlFileName;
    }

    /**
     * Sets the XML file to be parsed.
     *
     * @param xmlFileName
     * @return <code>True</code> if the file is readable,
     *         <code>false</code> if not.
     */
    public boolean setXMLFileName(String xmlFileName) {
        File test = new File(xmlFileName);
        if (test.canRead()) {
            this.xmlFileName = xmlFileName;
            test = null;
            return true;
        } else {
            test = null;
            if (this.verbosity > 0) {
                System.err.println(this.getClass() + ": Warning: Could not open "
                        + xmlFileName
                        + "for reading!");
            }
            return false;
        }
    }

    /**
     * Gets the currently set level of verbosity of this instance. The higher
     * the value the more information is written to stderr.
     *
     * @return The level of verbosity.
     */
    public int getVerbosity() {
        return this.verbosity;
    }

    /**
     * Sets the currently set level of verbosity of this instance. The higher
     * the value the more information is written to stderr.
     *
     * @param verbosity The level of verbosity.
     */
    public void setVerbosity(int verbosity) {
        this.verbosity = verbosity;
    }


} // class

