name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'oracle'
          cache: maven
      - name: Install MPJ to Maven Local
        run: |
          mvn -B install:install-file -Dfile=libs/mpj.jar -DgroupId=org.mpjexpress -DartifactId=mpj -Dversion=0.44 -Dpackaging=jar
          mvn -B install:install-file -Dfile=libs/mpi.jar -DgroupId=org.mpjexpress -DartifactId=mpi -Dversion=0.44 -Dpackaging=jar

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests -Djacoco.skip=true

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            **/target/*.jar
